name: build docs

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-docs.yml'
      - 'docs/**'
env:
  PNPM_VERSION: 8.4.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: jasonraimondi/ts-oauth2-server
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm docs:build
          BUILD_DIR: docs/.vitepress/dist/
