name: build docs

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-docs.yml'
      - 'docs/**'
env:
  PNPM_VERSION: 8.4.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm docs:build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/.vitepress/dist/'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
